Allowing streams for large uploads to google storage via the GCS client
walmartlabs/cookie-cutter pull request #369
Opened 2022-11-09 17:07 UTC by k0p04ku

**Testing**

![image](https://user-images.githubusercontent.com/116756889/200894902-0e5f9bc6-f1a0-433c-9922-61e5ab3244cd.png)

I was able to successfully stream an image into GS.

2022-11-09 17:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/walmartlabs/cookie-cutter?pullRequest=369) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/walmartlabs/cookie-cutter?pullRequest=369) before we can accept your contribution.<br/><hr/>**kishan.patel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/walmartlabs/cookie-cutter?pullRequest=369) it.</sub>

2022-11-09 17:35 UTC, cross311 requested changes
I think this is a good change, just want to see testing more concrete that it works.

2022-11-11 07:40 UTC, k0p04ku commented on packages/gcp/src/__test__/GcsClient.test.ts
> +            await expect(client.putObjectAsStream(span.context(), mockStream, "fileName")).resolves.toBe(
I've added an assertion for this now.

2022-11-11 15:49 UTC, k0p04ku commented
> I think this is a good change, just want to see testing more concrete that it works.

I've added an assertion regarding what exactly we're reading and writing into GS.

2022-11-11 15:57 UTC, prachi30 commented on packages/gcp/src/__test__/GcsClient.test.ts
>          it("rejects on error from gcs for put", async () => {
nit: can you re word it to be specific to put object?

2022-11-11 16:33 UTC, prachi30 commented on packages/gcp/src/__test__/GcsClient.test.ts
>          it("rejects on error from gcs for put", async () => {
```suggestion
        it("rejects on error from gcs for putting objects", async () => {
```

2022-11-11 16:46 UTC, k0p04ku commented on packages/gcp/src/__test__/GcsClient.test.ts
>          it("rejects on error from gcs for put", async () => {
Fixed

2022-11-17 15:44 UTC, prachi30 approved these changes

2022-11-17 15:56 UTC, prachi30 approved these changes

2022-11-18 14:59 UTC, cross311 requested changes

2022-11-18 14:59 UTC, cross311 commented on packages/gcp/src/index.ts
> +    putObjectAsStream(context: SpanContext, stream: Readable, key: string): Promise<void>;
Mind keeping variable names consistant
```suggestion
    putObjectAsStream(spanContext: SpanContext, stream: Readable, key: string): Promise<void>;
```

2022-11-18 17:08 UTC, k0p04ku commented on packages/gcp/src/index.ts
> +    putObjectAsStream(context: SpanContext, stream: Readable, key: string): Promise<void>;
Fixed.

2022-11-18 17:24 UTC, cross311 approved these changes

2022-11-18 20:28 UTC, merged