add orderingKey for pubSub sink
walmartlabs/cookie-cutter pull request #392
Opened 2024-02-13 17:11 UTC by amitlopes-walmart

2024-02-13 17:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/walmartlabs/cookie-cutter?pullRequest=392) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/walmartlabs/cookie-cutter?pullRequest=392) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/walmartlabs/cookie-cutter?pullRequest=392) it.</sub>

2024-02-15 15:50 UTC, butorine requested changes

2024-02-15 15:50 UTC, butorine commented on packages/gcp/src/PubSubSink.ts
> +    OrderingKey = "orderingKey",
I would rename this to `Key = "orderingKey"` to be consistent with kafka nomenclature

2024-02-15 15:50 UTC, butorine commented on packages/gcp/src/PubSubSink.ts
> +            topic.messageOrdering = !!formattedMsg.orderingKey;
This should only be set if `topic.messageOrdering` is false.  If it's already true, then bypass.  This way if some messages contain a key, but some do not, then all will be published with an ordering key

2024-02-15 15:50 UTC, butorine commented on packages/gcp/src/PubSubSink.ts
> +    payloadWithAttributes: IPayloadWithAttributes[];
Make this plural, please: `payloadsWithAttributes`

2024-02-16 21:03 UTC, plameniv commented on packages/gcp/src/__test__/PubSubSink.test.ts
> +    it("with orderingKey", async () => {
Can you make sure to have an empty line before each `it(...` line?

2024-02-16 21:13 UTC, plameniv commented on packages/gcp/src/__test__/PubSubSink.test.ts
> +    it("without orderingKey", async () => {
I think you can just move a couple of the expects which check for `no orderingKey` into the 2 already existing positive tests which don't use an ordering key.
And remove this `it(...` segment.

2024-02-16 22:22 UTC, plameniv approved these changes
LGTM!

2024-02-16 22:23 UTC, merged